//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coat
    {
        public int CoatsID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DescriptionID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> SeasonID { get; set; }
        public string Material { get; set; }
        public string Photo { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Description Description { get; set; }
        public virtual Season Season { get; set; }
    }
}
