//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dress()
        {
            this.Outfits = new HashSet<Outfit>();
        }
    
        public int DressesID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DescriptionID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> SeasonID { get; set; }
        public string Photo { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Description Description { get; set; }
        public virtual Season Season { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> Outfits { get; set; }
    }
}
