//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outfit
    {
        public int OutfitsID { get; set; }
        public string Name { get; set; }
        public Nullable<int> TopsID { get; set; }
        public Nullable<int> BottomsID { get; set; }
        public Nullable<int> DressesID { get; set; }
        public Nullable<int> LegwearID { get; set; }
        public Nullable<int> FootwearID { get; set; }
        public Nullable<int> AccessoriesID { get; set; }
        public Nullable<int> JewelryID { get; set; }
        public Nullable<int> CoatID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> SeasonID { get; set; }
        public Nullable<int> DescriptionID { get; set; }
        public Nullable<int> OccasionID { get; set; }
        public string Photo { get; set; }
    
        public virtual Bottom Bottom { get; set; }
        public virtual Color Color { get; set; }
        public virtual Description Description { get; set; }
        public virtual Description Description1 { get; set; }
        public virtual Dress Dress { get; set; }
        public virtual Jewelry Jewelry { get; set; }
        public virtual Legwear Legwear { get; set; }
        public virtual Legwear Legwear1 { get; set; }
        public virtual Outfit Outfits1 { get; set; }
        public virtual Outfit Outfit1 { get; set; }
        public virtual Outfit Outfits11 { get; set; }
        public virtual Outfit Outfit2 { get; set; }
        public virtual Season Season { get; set; }
        public virtual Top Top { get; set; }
    }
}
