//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeTracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WardrobeTrackerEntities : DbContext
    {
        public WardrobeTrackerEntities()
            : base("name=WardrobeTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bottom> Bottoms { get; set; }
        public virtual DbSet<Coat> Coats { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Description> Descriptions { get; set; }
        public virtual DbSet<Dress> Dresses { get; set; }
        public virtual DbSet<Embellishment> Embellishments { get; set; }
        public virtual DbSet<Footwear> Footwears { get; set; }
        public virtual DbSet<Jewelry> Jewelries { get; set; }
        public virtual DbSet<Legwear> Legwears { get; set; }
        public virtual DbSet<Occasion> Occasions { get; set; }
        public virtual DbSet<Outfit> Outfits { get; set; }
        public virtual DbSet<Pantaloon> Pantaloons { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<Sho> Shoes { get; set; }
        public virtual DbSet<Top> Tops { get; set; }
        public object Photos { get; internal set; }
    }
}
